# Generated by Django 5.2.10 on 2026-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('TABLET', 'Tablet')], default='LAPTOP', max_length=20),
        ),
    ]
