# Generated by Django 5.2.10 on 2026-02-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_email', models.CharField(max_length=255)),
                ('submitted_for', models.CharField(max_length=20)),
                ('asset_owner_email', models.CharField(max_length=255)),
                ('asset_id', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
