# Generated by Django 5.2.10 on 2026-02-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submitted_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='serial_number',
            new_name='serial_no',
        ),
        migrations.AlterField(
            model_name='submission',
            name='asset_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_for',
            field=models.CharField(max_length=50),
        ),
    ]
